- name: Launch app
  community.docker.docker_container:
    name: simple-api
    image: constant4n/tp-devops-simple-api
    pull: always
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://tp-db:5432/db
      SPRING_DATASOURCE_USERNAME: "{{ postgres_user }}"
      SPRING_DATASOURCE_PASSWORD: "{{ postgres_password }}"
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python